### ISSUE TITLE
Message Requirements

### ISSUE THREAD

**Issue by jameshawkinsjr** [jameshawkinsjr/hype#3]
# Messages

### Create

- [x] Users can send messages
- [x] Users can hit the "Enter" key to send a message
- [x] Created messages persist to the server

### Read

- [x] Users can see messages they have sent
- [x] Users can see messages that others have sent
- [x] Users receive messages from ActionCable in real time
- [x] Messages only show up in the appropriate chatrooms

### Update

- [x] Users can edit their own messages
- [x] Users can't edit messages that other people have written

### Delete

- [x] Users can delete their own messages
- [x] Users can't delete messages that other people have written

## Style

- [x] The message window should look exactly like the actual site
- [x] When errors are displayed, most elements should not move around the page
- [x] Remove Redux logger and all console.log()'s from production

**Comment by ronilbhatia** [comment]
Overall it looks really great man. You are making great progress, so keep up the good work! I don't have too many comments and honestly everything is looking good enough to close out the issue. Here are two things you should deal with at some point, though:

* When I login as Michael Scott or Jim Halpert, I get redirected to the Party Planning Committee chatroom, but the headers at the top of the chat are blank. I noticed that for both of these users, this chatroom doesn't show up in his sidebar. When I login as Pam, however everything displays fine, and the chat does show up in the sidebar. I'm assuming there's some relation here since you're probably fetching that information for your sidebar index, and relying on it being available when you enter the chatroom. You should be fetching this information when you go to the chatroom, in case it isn't already in state to prevent against this. I won't make you fix this now, but should definitely be fixed for your chatroom MVP.
![screen shot 2019-03-05 at 9 18 37 am](https://user-images.githubusercontent.com/32026924/53825073-47f62200-3f2a-11e9-9d03-ceb627c42a1b.png)

* Redux logger is still visible in production. If you want a sophisticated way to make sure it never shows up in production, and not have to remove it add it back every heroku push, refactor your `configureStore` function to look like this
```js
const configureStore = (preloadedState = {}) => {
  let middleware = [thunk];
  if (process.env.NODE_ENV !== 'production') {
    middleware = [...middleware, logger];
  }
  return createStore(
    rootReducer,
    preloadedState,
    applyMiddleware(...middleware)
  );
};
```
* I see these errors in the console if I submit an empty mesage
![screen shot 2019-03-05 at 9 07 50 am](https://user-images.githubusercontent.com/32026924/53823353-74a83a80-3f26-11e9-8ad1-bfb56d9ab034.png)
